server:
  port: 9090
eureka:
  instance:
    preferIpAddress: true
    instance-id: ${spring.application.name}:${random.uuid}
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/
